name: Forex Signals

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:


      
      - name: Show logs
        if: always()
        run: echo "Job completed with status ${{ job.status }}"
